from typing import Protocol
from shared.models.prediction import PredictionAlert
from shared.models.info_config import ConfigStats
from shared.models.user import User

class BackendProtocol(Protocol):
    """Contrato que el frontend espera. Mock y real lo implementan."""
    def get_alerts(self) -> list[PredictionAlert]: ...
    def get_product_detail(self, barcode: str) -> PredictionAlert: ...
    def get_dashboard_stats(self) -> dict: ...
    def is_first_start(self) -> bool: ...
    def register_user(self, user: User) -> dict: ...
    def create_configurations(self) -> bool: ...
    def get_sales_history(self) -> list[dict]: ...
    def get_app_stats(self) -> ConfigStats: ...
    def get_server_status(self) -> bool: ...
 
    